### ISSUE TITLE
dynamiczna aktualizacja plików .md

### ISSUE THREAD

**Issue by dudzislaw** [Miastodwa/jazdow.pl#8]
nie działa autokompilacja "site_title" z pliku data.md - sprawa kompletnie nieistotna, ponowne uruchomienie gulpa rozwiązuje problem #
edit:
ogólnie pliki .md się nie kompilują automatycznie?

**Comment by jfcieslak** [comment]
kompilują się przy `gulp` i przy `gulp data`
